# Generated by Django 5.2.1 on 2025-05-17 03:09

import django.db.models.deletion
import documents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("identification", models.CharField(max_length=20, unique=True)),
                ("date_of_birth", models.DateField()),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("medical_history", "Historia Clínica"),
                            ("disability", "Incapacidad"),
                            ("prescription", "Prescripción"),
                            ("other", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(upload_to=documents.models.get_file_path)),
                (
                    "secure_file",
                    models.FileField(blank=True, null=True, upload_to="secured/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_hash",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                (
                    "verification_code",
                    models.CharField(blank=True, max_length=10, null=True, unique=True),
                ),
                ("is_signed", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="documents.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DocumentVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("verified_at", models.DateTimeField(auto_now_add=True)),
                ("verified_by_ip", models.GenericIPAddressField()),
                ("is_valid", models.BooleanField(default=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verifications",
                        to="documents.document",
                    ),
                ),
            ],
        ),
    ]
